### ISSUE TITLE
Unable to use EL 2.2 syntax

### ISSUE THREAD

**Issue by Robbe64** [Zergleb/Spring-Boot-JSF-Example#1]
Hi, thanks for all at first :)

I wasn't able to get this example running with EL 2.2 syntax.
To test this just edit the test.xhtml file and add the brackets shown below.
# {jsfController.doSomething()}

It would be great if you can help finding a solution for that.

**Comment by Zergleb** [comment]
I'm sorry that I took so long to respond to this. I'm also sorry I didn't upload this to the repo in the first place. In my own application I have updated the build.gradle to read 

```
compile group: 'javax.el', name: 'el-api', version: '1.0'
compile "org.glassfish.web:el-impl:2.2"
```

instead of 

```
compile group: 'javax.el', name: 'el-api', version: '1.0'
compile group: 'com.sun.el', name: 'el-ri', version: '1.0'
compile "javax.servlet.jsp:jsp-api:2.1"
```

I'll push this update to the repository right now. Thanks for finding this and pointing it out.

**Comment by Zergleb** [comment]
The fix is in, please test this out for me(Just because avoiding doing qa on my own issues) and then I'll close the issue, thanks.
